on:
  push:

name: Build

jobs:

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/spaceapi-community/spaceapi-sensor-logger:latest .
